# PostgreSQL. Versions 8.2 and up are supported.

development:
  adapter: postgresql
  encoding: unicode
  database: superlatives_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: superlatives_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: superlatives_production
  pool: 5
  username:
  password:
